site_name: Raspberry Pi Projects
theme:
  name: material
  palette: 
    scheme: default
    primary: amber
    accent: red
  logo: images/raspberry-pi-logo.png

plugins:
  - drawio_file

nav:
  - Home: index.md
  - Ansible: ansible/ansible-index.md
  - Python:
    - GPIO Local: python/gpio-local/index.md
    - GPIO Remote: python/gpio-remote/index.md
