site_name: Raspberry Pi Projects
site_description: Raspberry Pi Projects
site_author: belcebus
site_url: https://belcebus.github.io/raspberrypi-projects/
repo_url: https://github.com/belcebus/raspberrypi-projects

theme:
  favicon: images/raspberry-pi-logo.png
  features:
    - content.code.copy        # Copy code blocks to clipboard
    - content.code.annotate    # Annotate code blocks
  logo: images/raspberry-pi-logo.png
  name: material
  palette: 
    scheme: default
    primary: amber
    accent: red
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - drawio_file

nav:
  - Home: index.md
  - Ansible: ansible/ansible-index.md
  - Python:
    - GPIO Local: python/gpio-local/index.md
    - GPIO Remote: python/gpio-remote/index.md
