---
- name: Raspberry funny stuff playbook
  hosts: raspberry
  tasks:
    - name: check if pihole is already installed
      ansible.builtin.command:
        argv:
          - "pihole"
          - "-v"
      ignore_errors: true
      register: pihole_version_command

    - name: create directory to store pihole installation script
      ansible.builtin.file:
        path: /home/{{ raspberry_default_ssh_user }}/.pihole/
        group: "{{ raspberry_default_ssh_user }}"
        owner: "{{ raspberry_default_ssh_user }}"
        state: directory
      when: pihole_version_command.failed == true

    - name: download pihole install script
      ansible.builtin.get_url:
        dest: "/home/{{ raspberry_default_ssh_user }}/.pihole/basic-install.sh"
        group: "{{ raspberry_default_ssh_user }}"
        owner: "{{ raspberry_default_ssh_user }}"
        url: https://install.pi-hole.net
        mode: "u+rwx"
      when: pihole_version_command.failed == true

    - name: create directory to store pihole install configuration
      become: true
      ansible.builtin.file:
        path: /etc/pihole/
        state: directory
      when: pihole_version_command.failed == true

    - name: create /etc/pihole/setupVars.conf file for pihole installation
      become: true
      ansible.builtin.copy:
        src: "{{playbook_dir}}/files/setupVars.conf"
        dest: "/etc/pihole/setupVars.conf"
      when: pihole_version_command.failed == true

    - name: prepare setupVars.conf
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/pihole/setupVars.conf"
        line: "{{item.value}}"
        regexp: "{{item.key}}"
        state: present
      with_items:
        - {key: "IPV4_ADDRESS", value: "IPV4_ADDRESS={{new_static_ip}}"}
        - {key: "PIHOLE_INTERFACE", value: "PIHOLE_INTERFACE={{wlan_interface}}"}
      when: pihole_version_command.failed == true

    - name: install pihole
      become: true
      ansible.builtin.command:
        argv:
          - "/home/{{ raspberry_default_ssh_user }}/.pihole/basic-install.sh"
          - "--unattended"
      when: pihole_version_command.failed == true

    - name: change pihole default password
      become: true
      ansible.builtin.command:
        argv:
          - "pihole"
          - "-a"
          - "-p"
          - "{{new_pihole_pass}}"
      vars:
        new_pihole_pass: "{{new_pihole_pass}}"
      when: pihole_version_command.failed == true
    
